# Generated by Django 4.2.3 on 2023-10-18 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment_grading',
            name='grading_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment_grading',
            name='marks',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='assignment_grading',
            name='status',
            field=models.CharField(choices=[('Pass', 'PASS'), ('Not Passed', 'FAIL'), ('Pending', 'PENDING')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='editor',
            field=models.ManyToManyField(default=None, to='course.author'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='category_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='editor',
            field=models.ManyToManyField(default=None, to='course.author'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='editor',
            field=models.ManyToManyField(default=None, to='course.author'),
        ),
        migrations.AddField(
            model_name='module',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='module_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='editor',
            field=models.ManyToManyField(default=None, to='course.author'),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unit_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='editor',
            field=models.ManyToManyField(default=None, to='course.author'),
        ),
        migrations.AddField(
            model_name='video',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='video_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='editor',
            field=models.ManyToManyField(default=None, to='course.author'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_updated_by', to='course.author'),
        ),
        migrations.AlterField(
            model_name='assignment_grading',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_grader', to='course.author'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_updated_by', to='course.author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_updated_by', to='course.author'),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_updated_by', to='course.author'),
        ),
        migrations.AlterField(
            model_name='module',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_updated_by', to='course.author'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_updated_by', to='course.author'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_updated_by', to='course.author'),
        ),
    ]
