# Generated by Django 4.2.3 on 2023-09-06 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Grading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(default=None, max_length=3)),
                ('grading_datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('comments', models.TextField()),
                ('status', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL'), ('pending', 'PENDING')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment_Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('enrollment_end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='question_option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quiz_question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz_Submission',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='units',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='units',
            name='modules',
        ),
        migrations.AddField(
            model_name='assignment',
            name='Number_of_members',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_team_submission_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignment',
            name='marks',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='assignment',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.units'),
        ),
        migrations.AddField(
            model_name='assignment_submission',
            name='assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.assignment'),
        ),
        migrations.AddField(
            model_name='assignment_submission',
            name='content',
            field=models.FileField(default=None, upload_to='content/'),
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='course.category'),
        ),
        migrations.AddField(
            model_name='courses',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='courses',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courses',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='files',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='files',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='files',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='files',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='files',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='files',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='module',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='units',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='units',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='units',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.module'),
        ),
        migrations.AddField(
            model_name='units',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='videos',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='videos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='videos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment_submission',
            name='submiission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='files',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.units'),
        ),
        migrations.AlterField(
            model_name='module',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='units',
            name='deleted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videos',
            name='unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.units'),
        ),
        migrations.DeleteModel(
            name='Question_Option',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='Quiz_Question',
        ),
        migrations.AddField(
            model_name='enrollement',
            name='course',
            field=models.ManyToManyField(default=None, to='course.courses'),
        ),
        migrations.AddField(
            model_name='assignment_partners',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.assignment'),
        ),
        migrations.AddField(
            model_name='assignment_grading',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.assignment_submission'),
        ),
    ]
