# Generated by Django 4.2.3 on 2023-10-20 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_alter_assignment_created_by_alter_assignment_editor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_number', to='course.assignment')),
                ('partners', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
