# Generated by Django 4.2.4 on 2023-10-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_assignment_number_of_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Number_of_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_team_submission_allowed',
            field=models.BooleanField(blank=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='assignment_submission',
        #     name='content',
        #     field=models.FileField(blank=True, null=True, upload_to='content/'),
        # ),
        
    ]
