# Generated by Django 4.2.3 on 2023-10-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_assignment_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, null=True, upload_to='assignment_file'),
        ),
        migrations.AddField(
            model_name='assignment_submission',
            name='submission_time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='is_team_submission_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
