# Generated by Django 4.2.3 on 2023-10-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_assignment_number_of_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submission',
            name='submission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
