# Generated by Django 4.2.3 on 2023-10-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_assignment_assignment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_grading',
            name='assignment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.assignment'),
            preserve_default=False,
        ),
    ]
