# Generated by Django 4.2.3 on 2023-10-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_assignment_submission_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_submission',
            name='submission_date',
            field=models.DateField(auto_now=True, default=None),
            preserve_default=False,
        ),
    ]
