# Generated by Django 4.2.3 on 2023-10-09 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_alter_assignment_submission_submission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_grading',
            name='user',
        ),
        migrations.AlterField(
            model_name='assignment_grading',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_grader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment_grading',
            name='grading_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assignment_grading',
            name='marks',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='assignment_grading',
            name='status',
            field=models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL'), ('pending', 'PENDING')], default='pending', max_length=50),
        ),
    ]
