# Generated by Django 4.2.3 on 2023-10-25 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_assignment_grading_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Partners_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.assignment')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment_partners',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_number', to='course.assignment_partners_group'),
        ),
    ]
