# Generated by Django 4.2.3 on 2023-10-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_assignment_partners_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_partners',
            old_name='assignment',
            new_name='assignment_group',
        ),
    ]
