# Generated by Django 4.2.3 on 2023-10-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_assignment_grading_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment_grading',
            name='grading_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
