# Generated by Django 4.2.3 on 2023-10-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_assignment_grading_grading_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_grading',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
    ]
