# Generated by Django 4.2.3 on 2023-10-25 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_rename_assignment_partners_group_assignment_partners_assignment_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_partners',
            old_name='assignment_group',
            new_name='assignment_partners_group',
        ),
    ]
