# Generated by Django 4.2.3 on 2023-10-25 13:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0012_rename_assignment_partners_group_assignment_group_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_Partner',
            new_name='Assignment_Partners',
        ),
        migrations.RenameModel(
            old_name='Assignment_Group',
            new_name='Assignment_Partners_Group',
        ),
        migrations.RenameField(
            model_name='assignment_partners',
            old_name='assignment_partners_group',
            new_name='assignment_group',
        ),
    ]
