# Generated by Django 4.2.3 on 2023-10-25 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0013_rename_group_partner_assignment_partners_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment_Partners',
            new_name='Assignment_Partner',
        ),
        migrations.RenameModel(
            old_name='Assignment_Partners_Group',
            new_name='Assignment_Partner_Group',
        ),
        migrations.RenameField(
            model_name='assignment_partner',
            old_name='assignment_group',
            new_name='assignment_partner_group',
        ),
    ]
