# Generated by Django 4.2.3 on 2023-10-25 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0014_rename_assignment_partners_assignment_partner_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment_Partner',
            new_name='Assignment_Partners',
        ),
        migrations.RenameModel(
            old_name='Assignment_Partner_Group',
            new_name='Assignment_Partners_Group',
        ),
        migrations.RenameField(
            model_name='assignment_partners',
            old_name='assignment_partner_group',
            new_name='assignment_group',
        ),
    ]
