# Generated by Django 4.2.3 on 2023-10-26 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0015_rename_assignment_partner_assignment_partners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='assignment_grading',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='course',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='file',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='file',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='module',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='module',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='video',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='editor',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='course_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='file_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='module_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unit_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='video_created_by', to='course.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment_grading',
            name='grader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_grader', to='course.author'),
        ),
    ]
