# Generated by Django 4.2.3 on 2023-10-26 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_assignment_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_created_by', to='course.author'),
            preserve_default=False,
        ),
    ]
