# Generated by Django 4.2.3 on 2023-10-30 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_assignment_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_grading',
            name='grader',
        ),
        migrations.AddField(
            model_name='assignment_grading',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_grading_creator', to='course.author'),
        ),
        migrations.AddField(
            model_name='assignment_partners',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_partners_creator', to='course.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment_partners_group',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_partners_group_creator', to='course.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_creator', to='course.author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_creator', to='course.author'),
        ),
        migrations.AlterField(
            model_name='file',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_creator', to='course.author'),
        ),
        migrations.AlterField(
            model_name='module',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_creator', to='course.author'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_creator', to='course.author'),
        ),
        migrations.AlterField(
            model_name='video',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_creator', to='course.author'),
        ),
    ]
