# Generated by Django 4.2.4 on 2023-08-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                default=None, max_length=150, null=True, unique=True
            ),
        ),
    ]
