# Generated by Django 4.2.4 on 2023-09-04 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_team"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Team",
        ),
    ]
