# Generated by Django 4.2.4 on 2023-09-04 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="created_by",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="team",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="team",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
