# Generated by Django 4.2.4 on 2023-09-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_team_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="accounts.team"
            ),
        ),
    ]
