# Generated by Django 4.2.4 on 2023-09-05 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_customuser_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="team_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="accounts.team"
            ),
        ),
    ]
