# Generated by Django 4.2.4 on 2023-09-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_team_users_alter_customuser_teams"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="teams",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="accounts.team"
            ),
        ),
    ]
