# Generated by Django 4.2.4 on 2023-09-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
        ("accounts", "0017_delete_teammembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="course.courses"
            ),
        ),
    ]
