# Generated by Django 4.2.4 on 2023-09-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
        ("accounts", "0018_team_courses"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="course.courses"
            ),
        ),
    ]
