# Generated by Django 4.2.4 on 2023-09-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
        ("accounts", "0019_customuser_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="users",
        ),
        migrations.AddField(
            model_name="customuser",
            name="courses",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="course.courses"
            ),
        ),
    ]
